org: kyoheiu
app: ltd-integration
service: sls-alexa
frameworkVersion: "3"

useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1

functions:
  mySkill:
    handler: src/index.handler
    events:
      - alexaSkill: ${env:ALEXA_SKILL_ID}

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
